return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "css-lsp",
        "vue-language-server",
        "clangd",
        "cmakelint",
        "delve",
        "dockerls",
        "gofumpt",
        "goimports",
        "gopls",
        "eslint",
        "html",
        "jsonls",
        "tsserver",
        "marksman",
        "js-debug-adapter",
        "lua_ls",
        "markdownlint",
        "neocmakelsp",
        "shfmt",
        "stylua",
        "tailwindcss",
        "volar",
        "yamlls",
      },
    },
  },
}
